version: '3.4'

networks:
  application:

services:
  nginx:
    hostname: 'nginx' 
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    networks:
      - application
    volumes:
      - ./application/:/app
    ports:
      - 80:80
    depends_on:
      - asgi

  asgi:
    hostname: 'asgi'
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/asgi/Dockerfile
    networks:
      - application
    volumes:
      - ./application:/app
    environment:
      - REDIS_HOST=redis
    depends_on:
      - database
      - redis

  database:
    hostname: 'database'
    image: postgres:12.4-alpine
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - application
    environment:
      - POSTGRES_PASSWORD=pia
      - POSTGRES_USER=pia
    volumes:
      - ./data:/var/lib/postgresql/data

  redis:
    restart: unless-stopped
    image: redis:alpine
    volumes:
      - ./storage/redis:/data
    networks:
      - application
    command: redis-server --appendonly yes