version: '3.4'

networks:
  application:

services:
  nginx:
    hostname: 'nginx' 
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    networks:
      - application
    volumes:
      - ./application/:/app
    ports:
      - 80:80
    depends_on:
      - uwsgi

  uwsgi:
    hostname: 'uwsgi'
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/uwsgi/Dockerfile
    networks:
      - application
    volumes:
      - ./application:/app
    depends_on:
      - database

  database:
    hostname: 'database'
    image: postgres:12.4-alpine
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - application
    environment:
      - POSTGRES_PASSWORD=pia
      - POSTGRES_USER=pia
    volumes:
      - ./data:/var/lib/postgresql/data