# Generated by Django 3.1.4 on 2020-12-30 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': [('vote', 'Can vote in poll')]},
        ),
    ]
