# Generated by Django 3.1.5 on 2021-01-11 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0002_userrequests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friends',
            options={'verbose_name': 'Přátelé', 'verbose_name_plural': 'Přátelé'},
        ),
        migrations.AlterModelOptions(
            name='userrequests',
            options={'verbose_name': 'Požadavek uživatele', 'verbose_name_plural': 'Požadavky uživatelů'},
        ),
    ]
