# Generated by Django 3.1.5 on 2021-01-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0004_auto_20210111_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequests',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
