# Generated by Django 3.1.5 on 2021-01-13 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0008_auto_20210113_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresets',
            name='time_sent',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='time sent'),
        ),
    ]
