# Generated by Django 3.1.5 on 2021-01-13 09:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0009_passwordresets_time_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresets',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
