# Generated by Django 3.1.5 on 2021-01-15 06:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0010_auto_20210113_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2048)),
                ('time_sent', models.DateTimeField(default=django.utils.timezone.now, verbose_name='time sent')),
            ],
            options={
                'verbose_name': 'Oznámení',
                'verbose_name_plural': 'Oznámení',
            },
        ),
    ]
